id = "laravel-support"
name = "Laravel Support"
version = "0.1.0"
schema_version = 1
authors = ["Akila Madhushanka"]
description = "Laravel tools: Blade syntax, Artisan commands, routes autocomplete"
repository = "https://github.com/akilama471/zed-laravel-extension"

[language_servers.laravel-lsp]
name = "Laravel LSP"
languages = ["PHP", "Blade"]
