id = "laravel-support"
name = "Laravel Support"
version = "0.1.0"
schema_version = 1
authors = ["Akila Madhushanka <developer.akila5@gmail.com>"]
description = "Laravel tools: Blade syntax highlighting, Artisan task runner, route & model autocomplete, and PHP language server integration."
repository = "https://github.com/akilama471/zed-laravel-extension"

[language_servers.laravel-lsp]
name = "Laravel LSP"
languages = ["PHP", "Blade"]
